import { apiClient, getEffectiveApiMode } from "./client";
import { createAuthApi } from "./endpoints/auth.api";
import { createLoansApi } from "./endpoints/loans.api";
import { createVerificationApi } from "./endpoints/verification.api";
import { createDocumentsApi } from "./endpoints/documents.api";
import { createDisbursementApi } from "./endpoints/disbursement.api";
import { createBankOfficialsApi } from "./endpoints/bank-officials.api";
import { createDsaApi } from "./endpoints/dsa.api";
import { createConnectorsApi } from "./endpoints/connectors.api";
import { createCustomersApi } from "./endpoints/customers.api";
import { createLeadsApi } from "./endpoints/leads.api";
import { createCrmApi } from "./endpoints/crm.api";
import { createCommissionsApi } from "./endpoints/commissions.api";
import { createReportsApi } from "./endpoints/reports.api";
import { createSettingsApi } from "./endpoints/settings.api";
import { createBranchesApi } from "./endpoints/branches.api";
import { createAreasApi } from "./endpoints/areas.api";
import { createUsersApi } from "./endpoints/users.api";

export * from "./client";
export * from "./endpoints/auth.api";
export * from "./endpoints/loans.api";
export * from "./endpoints/verification.api";
export * from "./endpoints/documents.api";
export * from "./endpoints/disbursement.api";
export * from "./endpoints/bank-officials.api";
export * from "./endpoints/dsa.api";
export * from "./endpoints/connectors.api";
export * from "./endpoints/customers.api";
export * from "./endpoints/leads.api";
export * from "./endpoints/crm.api";
export * from "./endpoints/commissions.api";
export * from "./endpoints/reports.api";
export * from "./endpoints/settings.api";
export * from "./endpoints/branches.api";
export * from "./endpoints/areas.api";
export * from "./endpoints/users.api";
export * from "./mock/mockDatabase";
export * from "./mock/mockAdapter";

const mode = getEffectiveApiMode();

export const authApi = createAuthApi(apiClient, mode);
export const loansApi = createLoansApi(apiClient, mode);
export const verificationApi = createVerificationApi(apiClient, mode);
export const documentsApi = createDocumentsApi(apiClient, mode);
export const disbursementApi = createDisbursementApi(apiClient, mode);
export const bankOfficialsApi = createBankOfficialsApi(apiClient, mode);
export const dsaApi = createDsaApi(apiClient, mode);
export const connectorsApi = createConnectorsApi(apiClient, mode);
export const customersApi = createCustomersApi(apiClient, mode);
export const leadsApi = createLeadsApi(apiClient, mode);
export const crmApi = createCrmApi(apiClient, mode);
export const commissionsApi = createCommissionsApi(apiClient, mode);
export const reportsApi = createReportsApi(apiClient, mode);
export const settingsApi = createSettingsApi(apiClient, mode);
export const branchesApi = createBranchesApi(apiClient, mode);
export const areasApi = createAreasApi(apiClient, mode);
export const usersApi = createUsersApi(apiClient, mode);
